Add huggingface embeddings
Aarhus-Psychiatry-Research/psycop-ml-utils pull request #221
Opened 2022-09-20 08:11 UTC by frillecode

- [ ] I have battle-tested on Overtaci (RMAPPS1279)
- [ ] I have bumped the version as described in the [wiki](https://www.notion.so/Setting-up-Poetry-on-your-local-machine-76647d75e8fa4d9ba553cbc2a49946d9#dca1e0f2ce934a49acd1851aaf882d75)

## Notes for reviewers

2022-09-20 09:18 UTC, frillecode commented
Den giver fejl fordi _sentence\_transformers_ library ikke er installeret. Har I en holdning til om jeg bør tilføje det eller om jeg skal omskrive koden, så den kun depender på _transformers_?

2022-09-21 09:32 UTC, HLasse commented
Det er nok bedre at omskrive til ren torch/transformers. 
1. Færre dependencies (selvom sentence_transformers er lille)
2. Jeg er ikke sikker på at `SentenceTransformers` implementeringen håndterer modeller der _ikke_ er SentenceTransformers. Dvs. hvis vi bare vil have embeddings fra en e.g. `danish-bert` vil det her sandsynligvis breake.

Jeg læser koden igennem og kommer med forslag 👍

2022-09-21 09:48 UTC, HLasse requested changes
Nice work Frida! 
A couple of things before merging:

1. Rewrite to pure torch/transformrs to make sure this works with different models (not just `SentenceTransformers`)
2. Extract your chunking logic to a loop and write a test for it
3. Update `load_synth_notes` to also take the HF featurizer as input
4. Write a test (in `tests/test_timeseriesflattener/test_add_values`) where you apply it on the synthetic data
5. Battle test it on Overtaci - check that it works on actual data

2022-09-21 09:48 UTC, HLasse commented on src/psycopmlutils/loaders/raw/load_text.py
>      # Load paraphrase-multilingual-MiniLM-L12-v2
```suggestion
```

2022-09-21 09:48 UTC, HLasse commented on src/psycopmlutils/loaders/raw/load_text.py
> +    model = SentenceTransformer(model_id)
Omskriv til ikke at bruge `SentenceTransformer`

2022-09-21 09:48 UTC, HLasse commented on src/psycopmlutils/loaders/raw/load_text.py
> +        if len(words) <= seq_length:
I suggest rewriting this to be based on the sequence length of the tokenized data, following tokenization using the HF model. In this way we won't have to tokenize the document twice

2022-09-21 09:48 UTC, HLasse commented on src/psycopmlutils/loaders/raw/load_text.py
> +            ]  # drop small remainder of shorter size
Move this to a separate function (and write a test for it). Use more descriptive variable names than `y` and `w`. Also needs to be rewritten a bit to work with the tokenized input

2022-09-27 13:34 UTC, closed without merging